// Code generated by MockGen. DO NOT EDIT.
// Source: docker.go
//
// Generated by this command:
//
//	mockgen -source=docker.go -destination=mocks/mock_docker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDockerBuilder is a mock of DockerBuilder interface.
type MockDockerBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockDockerBuilderMockRecorder
	isgomock struct{}
}

// MockDockerBuilderMockRecorder is the mock recorder for MockDockerBuilder.
type MockDockerBuilderMockRecorder struct {
	mock *MockDockerBuilder
}

// NewMockDockerBuilder creates a new mock instance.
func NewMockDockerBuilder(ctrl *gomock.Controller) *MockDockerBuilder {
	mock := &MockDockerBuilder{ctrl: ctrl}
	mock.recorder = &MockDockerBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDockerBuilder) EXPECT() *MockDockerBuilderMockRecorder {
	return m.recorder
}

// BuildImage mocks base method.
func (m *MockDockerBuilder) BuildImage(dockerFile, outputDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildImage", dockerFile, outputDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildImage indicates an expected call of BuildImage.
func (mr *MockDockerBuilderMockRecorder) BuildImage(dockerFile, outputDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildImage", reflect.TypeOf((*MockDockerBuilder)(nil).BuildImage), dockerFile, outputDir)
}
