// Code generated by MockGen. DO NOT EDIT.
// Source: github.go
//
// Generated by this command:
//
//	mockgen -source=github.go -destination=mocks/mock_github.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "lunch/domain/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGithubRepository is a mock of GithubRepository interface.
type MockGithubRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGithubRepositoryMockRecorder
	isgomock struct{}
}

// MockGithubRepositoryMockRecorder is the mock recorder for MockGithubRepository.
type MockGithubRepositoryMockRecorder struct {
	mock *MockGithubRepository
}

// NewMockGithubRepository creates a new mock instance.
func NewMockGithubRepository(ctrl *gomock.Controller) *MockGithubRepository {
	mock := &MockGithubRepository{ctrl: ctrl}
	mock.recorder = &MockGithubRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGithubRepository) EXPECT() *MockGithubRepositoryMockRecorder {
	return m.recorder
}

// PullGithubRepo mocks base method.
func (m *MockGithubRepository) PullGithubRepo(url, destPath string) (model.GithubRepo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullGithubRepo", url, destPath)
	ret0, _ := ret[0].(model.GithubRepo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullGithubRepo indicates an expected call of PullGithubRepo.
func (mr *MockGithubRepositoryMockRecorder) PullGithubRepo(url, destPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullGithubRepo", reflect.TypeOf((*MockGithubRepository)(nil).PullGithubRepo), url, destPath)
}
